secret_key_base: T8nR-e-3ZyGO6GSSQL90Rs16sQmpNLBMnA4XbM0V7WQ
port: 3000
name: nocturne
logging:
  severity: debug
  colorize: true
  filter:
    - password
    - confirm_password
  skip:
    -
  context:
    - request
    - session
    - headers
    - cookies
    - params

host: 0.0.0.0
port_reuse: false
process_count: 1
# ssl_key_file:
# ssl_cert_file:
redis_url: "redis://localhost:6379"
database_url: postgres://postgres:@localhost:5432/nocturne_test
session:
  key: amber.session
  store: signed_cookie
  expires: 0
smtp:
  enabled: false

secrets:
  description: Store your development secrets credentials and settings here.


